---
title: "R Notebook"
author: Ingrid
date: 17/08/2020
output: html_notebook
---
```{r}
# Load required Libraries

library(uwot)
library(Seurat)
library(dplyr)
library(patchwork)
library(ggplot2)
library(RColorBrewer)
library(harmony)
library(cowplot)
library(data.table)

#Set paths

mA5.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Kidney-UUO/"
Bleo2.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Lung-Bleo/"
BDL2.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-BDL/"
CCl4.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-CCl4/"

mA5Output.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Kidney-UUO/Outputs/"
Bleo2Output.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Lung-Bleo/Outputs/"
BDL2Output.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-BDL/Outputs/"
CCl4Output.path  <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-CCl4/Outputs/"

#Set date

#Today.date <- "070820"
Today.date <- "160820"
# Set colour palettes

mA5.colpal <- c("#CA9858",	"#FF7F00",	"#C8828D",	"#FFCA62")

Bleo2.colpal <- c("#9683B0",	"#6A3D9A",	"#C8828D",	"#DA98D6")

BDL2.colpal <- c("#8EB26E",	"#88BCB2",	"#33A02C",	"#00CDB3",	"#C8828D",	"#F4A1AF",	"#B2DF8A",	"#AFF1E1")

CCl4.colpal <- c("#74909E",	"#167EDB",	"#C8828D",	"#A6CEE3")
```

# Cluster annotation + Doublet Removal (i.e. making cleaned)
```{r}
#Load datasets
mA5 <- readRDS(paste0(mA5.path, Today.date, "_mA5_UMAP.RDS"))
Bleo2 <- readRDS(paste0(Bleo2.path, Today.date, "_Bleo2_UMAP.RDS"))
BDL2 <- readRDS(paste0(BDL2.path, Today.date, "_BDL2_UMAP.RDS"))
CCl4 <- readRDS(paste0(CCl4.path, Today.date, "_CCl4_UMAP.RDS"))

# Cluster and Lineage Annotation + Save
### cell type annotation ###
mA5_cluster.annotation <- c("Blood B cell 1", "Kidney macrophage 1", "Kidney macrophage 2", "UUO blood Ly6Chi monocyte", "Blood Ly6Clo monocyte", "CD8+ T cell 1", "Kidney macrophage 3", "Kidney macrophage 4", "Cd4+ T cell 1", "NK cell 1", "Kidney monocyte", "Healthy blood Ly6Chi monoyte", "Kidney cDC2 1", "Cd4+ T cell 2", "Kidney cDC2 2", "Kidney B cell", "Kidney cDC1", "Kidney proliferating macrophage 1", "Kidney proliferating macrophage 2", "Kidney IFN-primed macrophage", "Kidney endothelial cells", "Blood neutrophils", "NK cell 2", "pDC","Neutrophil/B cell doublet","Basophil","Proliferating","Neutrophil/T cell doublet", "ILC2", "CCR7+ cDC", "Cd8+ T cell 2", "Monocyte/T cell doublet", "Platelet")

names(mA5_cluster.annotation) <- levels(mA5)
mA5 <- RenameIdents(mA5, mA5_cluster.annotation)

mA5_cell.data <- data.table(barcode = colnames(mA5),
                        Cell.type = Idents(mA5))

mA5_cell.data <- data.frame(mA5_cell.data, row.names = mA5_cell.data$barcode)
mA5_cell.data$barcode <- NULL
mA5 <- AddMetaData(mA5, mA5_cell.data, col.name = "Cell.type")

### save annotated UMAP ###
annotated.umap.plot.split <- DimPlot(mA5, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5_aUMAP_cluster_OGIDsplit.png"), plot = annotated.umap.plot.split, width = 45, height = 10, units = "cm")

annotated.umap.plot.merge <- DimPlot(mA5, reduction = "umap", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5_aUMAP_cluster.png"), plot = annotated.umap.plot.merge, width = 30, units = "cm")


### cell lineage annotation ###
mA5_cell.data <- data.table(barcode = colnames(mA5),
                        Cell.type = Idents(mA5))

mA5_lineage.annotation <- c("B cell",	"MP",	"MP",	"MP",	"MP",	"T cell/ILC",	"MP",	"MP",	"T cell/ILC",	"T cell/ILC", "MP",	"MP",	"MP",	"T cell/ILC",	"MP",	"B cell",	"MP",	"MP",	"MP",	"MP",	"Endothelia",	"Neutrophil",	"T cell/ILC",	"MP",	"Doublet",	"Basophil",	"Proliferating",	"Doublet",	"T cell/ILC",	"MP",	"T cell/ILC",	"Doublet",	"Platelet")

mA5_lineage.data <- data.table(Cell.type = mA5_cluster.annotation, lineage = mA5_lineage.annotation)
meta.data <- merge(mA5_cell.data, mA5_lineage.data, by = "Cell.type")
meta.data <- data.frame(meta.data, row.names = meta.data$barcode)
meta.data$barcode <- NULL
meta.data$Cell.type <- NULL
mA5 <- AddMetaData(mA5, meta.data, col.name = "lineage")
# save annotated UMAP
lineage.umap.plot <- DimPlot(mA5, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5_aUMAP_lineage_OGIDsplit.png"), plot = lineage.umap.plot, width = 45, height = 10, units = "cm")

lineage.umap.plot <- DimPlot(mA5, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5_aUMAP_lineage.png"), plot = lineage.umap.plot, width = 30, units = "cm")

saveRDS(mA5, file = paste0(mA5.path, Today.date, "_mA5_annotated.RDS"))

#- Bleo2 -

### cell type annotation ###
Bleo2_cluster.annotation <- c("Blood B cell 1","Lung alveolar macrophage 1","Blood Ly6Chi Monocyte","Blood Ly6Clo Monocyte 1","Lung B Cell 1","Cd4+ T cell 1","NK cell 1", "Blood CD8+ T cell","Blood CD4+ T cell 2","Lung CD4+ T cell 2","Lung CD8+ T cell","Lcn2+ Monocyte","cDC1","cDC2","Lung interstitial macrophage 1","Lung Monocyte","Lung macrophage 3","Lung interstitial macrophage 2","Blood B cell 2","Blood Ly6Clo Monocyte 2","Proliferating T cell","Proliferating cDC","ILC2","CD8+ T cell 2","Proliferating Lung Alveolar macrophage","Blood IFN-primed Ly6Chi Monocyte","T cell/B cell doublet","Basophil","pDC","Lung macrophage 4","Lung endothelial cells","CCR7+ cDC","Lung alveolar macrophage 2")

names(Bleo2_cluster.annotation) <- levels(Bleo2)
Bleo2 <- RenameIdents(Bleo2, Bleo2_cluster.annotation)

Bleo2_cell.data <- data.table(barcode = colnames(Bleo2),
                             Cell.type = Idents(Bleo2))

Bleo2_cell.data <- data.frame(Bleo2_cell.data, row.names = Bleo2_cell.data$barcode)
Bleo2_cell.data$barcode <- NULL
Bleo2 <- AddMetaData(Bleo2, Bleo2_cell.data, col.name = "Cell.type")

### save annotated UMAP ###
annotated.umap.plot.split <- DimPlot(Bleo2, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Today.date, "_Bleo2_aUMAP_cluster_OGIDsplit.png"), plot = annotated.umap.plot.split, width = 45, height = 10, units = "cm")

annotated.umap.plot.merge <- DimPlot(Bleo2, reduction = "umap", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Today.date, "_Bleo2_aUMAP_cluster.png"), plot = annotated.umap.plot.merge, width = 30, units = "cm")


### cell lineage annotation ###
Bleo2_cell.data <- data.table(barcode = colnames(Bleo2),
                             Cell.type = Idents(Bleo2))

Bleo2_lineage.annotation <- c("B cell","MP","MP","MP","B cell","T cell/ILC","T cell/ILC","T cell/ILC","T cell/ILC","T cell/ILC", "T cell/ILC", "MP","MP","MP","MP","MP","MP","MP","B cell","MP","T cell/ILC","MP","T cell/ILC","T cell/ILC","MP","MP","Doublet","Basophil","MP","MP", "Endothelia","MP","MP")


Bleo2_lineage.data <- data.table(Cell.type = Bleo2_cluster.annotation, lineage = Bleo2_lineage.annotation)
Bleo2_meta.data <- merge(Bleo2_cell.data, Bleo2_lineage.data, by = "Cell.type")
Bleo2_meta.data <- data.frame(Bleo2_meta.data, row.names = Bleo2_meta.data$barcode)
Bleo2_meta.data$barcode <- NULL
Bleo2_meta.data$Cell.type <- NULL
Bleo2 <- AddMetaData(Bleo2, Bleo2_meta.data, col.name = "lineage")
# save annotated UMAP
lineage.umap.plot <- DimPlot(Bleo2, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename =  paste0(Bleo2Output.path, Today.date, "_Bleo2_aUMAP_lineage_OGIDsplit.png"), plot = lineage.umap.plot, width = 45, height = 10, units = "cm")

lineage.umap.plot <- DimPlot(Bleo2, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename =  paste0(Bleo2Output.path, Today.date, "_Bleo2_aUMAP_lineage.png"), plot = lineage.umap.plot, width = 30, units = "cm")


saveRDS(Bleo2, file = paste0(Bleo2.path, Today.date, "_Bleo2_annotated.RDS"))

#- BDL2 - ran later

BDL2 <- readRDS(paste0(BDL2.path, Today.date, "_BDL2_UMAP.RDS"))
 BDL2_cluster.annotation <- c("Liver Kupffer Cell 1",	"Blood Ly6Clo monocyte 1",	"BDL Blood Ly6Chi monocyte 1",	"Healthy Blood Ly6Chi monocyte 1",	"Liver macrophage 2",	"B cell 1",	"Liver macrophage 4",	"Liver macrophage 1",	"B cell 2",	"NK cell 1",	"BDL Blood Ly6Clo monocyte 1",	"CD8+ T cell 1",	"T cell 2",	"Cd4+ T cell 1",	"Proliferating",	"cDC2",	"NK cell 2",	"Neutrophil 1",	"Healthy Blood Ly6Chi monocyte 2",	"BDL Blood Ly6Chi monocyte 2",	"Liver Endothelial Cells",	"Liver macrophage 3",	"Platelet 1",	"pDC",	"Blood Ly6Clo monocyte 2",	"B cell 3",	"Blood IFN-primed Ly6Chi monocyte",	"Liver Kupffer Cell 2",	"cDC1",	"Neutrophil 2",	"Liver macrophage 5",	"Monocyte/B cell doublet",	"Basophil",	"Monocyte/B cell doublet 1",	"Monocyte/T cell doublet 2",	"Platelet 2")

 names(BDL2_cluster.annotation) <- levels(BDL2)
 BDL2 <- RenameIdents(BDL2, BDL2_cluster.annotation)

 BDL2_cell.data <- data.table(barcode = colnames(BDL2),
                             Cell.type = Idents(BDL2))

BDL2_cell.data <- data.frame(BDL2_cell.data, row.names = BDL2_cell.data$barcode)
BDL2_cell.data$barcode <- NULL
BDL2 <- AddMetaData(BDL2, BDL2_cell.data, col.name = "Cell.type")

### save annotated UMAP ###
annotated.umap.plot.split <- DimPlot(BDL2, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2_aUMAP_cluster_OGIDsplit.png"), plot = annotated.umap.plot.split, width = 45, height = 10, units = "cm")

annotated.umap.plot.merge <- DimPlot(BDL2, reduction = "umap", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2_aUMAP_cluster.png"), plot = annotated.umap.plot.merge, width = 30, units = "cm")

### cell lineage annotation ###
BDL2_cell.data <- data.table(barcode = colnames(BDL2),
                             Cell.type = Idents(BDL2))

BDL2_lineage.annotation <- c("MP",	"MP",	"MP",	"MP",	"MP",	"B cell",	"MP",	"MP",	"B cell",	"T cell/ILC",	"MP",	"T cell/ILC",	"T cell/ILC",	"T cell/ILC",	"Proliferating",	"MP",	"MP",	"MP",	"MP",	"MP",	"Endothelia",	"MP",	"Platelet",	"MP",	"MP",	"B cell",	"MP",	"MP",	"MP",	"Neutrophil",	"MP",	"Doublet",	"Basophil",	"Doublet",	"Doublet",	"Platelet")

BDL2_lineage.data <- data.table(Cell.type = BDL2_cluster.annotation, lineage = BDL2_lineage.annotation)
meta.data <- merge(BDL2_cell.data, BDL2_lineage.data, by = "Cell.type")

meta.data <- data.frame(meta.data, row.names = meta.data$barcode)
meta.data$barcode <- NULL
meta.data$Cell.type <- NULL

BDL2 <- AddMetaData(BDL2, meta.data, col.name = "lineage")

# save annotated UMAP
lineage.umap.plot <- DimPlot(BDL2, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2_aUMAP_lineage_OGIDsplit.png"), plot = lineage.umap.plot, width = 45, height = 10, units = "cm")

lineage.umap.plot <- DimPlot(BDL2, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2_aUMAP_lineage.png"), plot = lineage.umap.plot, width = 30, units = "cm")

saveRDS(BDL2, file = paste0(BDL2.path, Today.date, "_BDL2_annotated.RDS"))

#- CCl4 -

### cell type annotation ###
CCl4_cluster.annotation <- c("Red blood cell/myeloid doublet","Blood Ly6Clo monocyte", "CCl4 Blood Ly6Clo monocyte","Healthy Blood Ly6Chi monocyte", "B cell 1", "CD8+ T cell 1", "CCl4 Blood Ly6Chi monocyte 1", "Liver macrophage 1", "NK cell 1","Cd4+ T cell 1","pDC", "cDC2","Liver Kupffer Cell 1","cDC1","CCl4 Liver Kupffer Cell 2","Blood IFN-primed Ly6Chi monocyte","Liver monocyte","CCl4 Blood Ly6Chi monocyte 2","Neutrophil","CCl4 Blood Ly6Chi monocyte 3","NK cell 2","Proliferating","Liver Endothelial Cells","B cell 2","B cell 3","Liver CCR7+ cDC","Macrophage/endothelial Doublet","Basophil","CD8+ T cell 2","Monocyte/T cell doublet","Eosinophil")

names(CCl4_cluster.annotation) <- levels(CCl4)
CCl4 <- RenameIdents(CCl4, CCl4_cluster.annotation)

CCl4_cell.data <- data.table(barcode = colnames(CCl4),
                            Cell.type = Idents(CCl4))

CCl4_cell.data <- data.frame(CCl4_cell.data, row.names = CCl4_cell.data$barcode)
CCl4_cell.data$barcode <- NULL
CCl4 <- AddMetaData(CCl4, CCl4_cell.data, col.name = "Cell.type")

### save annotated UMAP ###
annotated.umap.plot.split <- DimPlot(CCl4, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Today.date, "_CCl4_aUMAP_cluster_OGIDsplit.png"), plot = annotated.umap.plot.split, width = 45, height = 10, units = "cm")

annotated.umap.plot.merge <- DimPlot(CCl4, reduction = "umap", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Today.date, "_CCl4_aUMAP_cluster.png"), plot = annotated.umap.plot.merge, width = 30, units = "cm")


### cell lineage annotation ###
CCl4_cell.data <- data.table(barcode = colnames(CCl4),
                            Cell.type = Idents(CCl4))

CCl4_lineage.annotation <- c("Doublet","MP","MP","MP","B cell","T cell/ILC","MP","MP","T cell/ILC","T cell/ILC","MP","MP","MP","MP","MP","MP","MP","MP","Neutrophil","MP","T cell/ILC","Proliferating","Endothelia","B cell","B cell","MP","Doublet","Basophil","T cell/ILC","Doublet","Eosinophil")


CCl4_lineage.data <- data.table(Cell.type = CCl4_cluster.annotation, lineage = CCl4_lineage.annotation)
meta.data <- merge(CCl4_cell.data, CCl4_lineage.data, by = "Cell.type")
meta.data <- data.frame(meta.data, row.names = meta.data$barcode)
meta.data$barcode <- NULL
meta.data$Cell.type <- NULL
CCl4 <- AddMetaData(CCl4, meta.data, col.name = "lineage")
# save annotated UMAP
lineage.umap.plot <- DimPlot(CCl4, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename =  paste0(CCl4Output.path, Today.date, "_CCl4_aUMAP_lineage_OGIDsplit.png"), plot = lineage.umap.plot, width = 45, height = 10, units = "cm")

lineage.umap.plot <- DimPlot(CCl4, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename =  paste0(CCl4Output.path, Today.date, "_CCl4_aUMAP_lineage.png"), plot = lineage.umap.plot, width = 30, units = "cm")

saveRDS(CCl4, file = paste0(CCl4.path, Today.date, "_CCl4_annotated.RDS"))
```
# Remove Doublet populations + Save
```{R}
mA5_cleaned <- subset(mA5, subset = lineage != "Doublet")
saveRDS(mA5_cleaned, file = paste0(mA5Output.path, Today.date, "_mA5_CLEANED.RDS"))
#
Bleo2_cleaned <- subset(Bleo2, subset = lineage != "Doublet")
saveRDS(Bleo2_cleaned, file = paste0(Bleo2Output.path, Today.date, "_Bleo2_CLEANED.RDS"))
#
BDL2_cleaned <- subset(BDL2, subset = lineage != "Doublet")
saveRDS(Bleo2_cleaned, file = paste0(BDL2Output.path, Today.date, "_BDL2_CLEANED.RDS"))
#
CCl4_cleaned <- subset(CCl4, subset = lineage != "Doublet")
saveRDS(CCl4_cleaned, file = paste0(CCl4Output.path, Today.date, "_CCl4_CLEANED.RDS"))

```
# Post-cleaned vis
```{r}

# Post-doublet visualisationss

mA5cleaned_UMAP <- DimPlot(mA5_cleaned, reduction = "umap",label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5CLEANED_aUMAP_cluster.png"), plot = mA5cleaned_UMAP, width = 30, units = "cm")

mA5cleaned_UMAP_split <- DimPlot(mA5_cleaned, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5CLEANED_aUMAP_cluster_OGIDsplit.png"), plot = mA5cleaned_UMAP_split, width = 45, height = 10, units = "cm")

mA5cleaned_lineage_split <- DimPlot(mA5_cleaned, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5CLEANED_aUMAP_lineage_OGIDsplit.png"), plot = mA5cleaned_lineage_split, width = 45, height = 10, units = "cm")

mA5cleaned_lineage <- DimPlot(mA5_cleaned, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.02) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Today.date, "_mA5CLEANED_aUMAP_lineage.png"), plot = mA5cleaned_lineage, width = 30, units = "cm")


#-

Bleo2cleaned_UMAP <- DimPlot(Bleo2_cleaned, reduction = "umap",label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Today.date, "_Bleo2CLEANED_aUMAP_cluster.png"), plot = Bleo2cleaned_UMAP, width = 30, units = "cm")

Bleo2cleaned_UMAP_split <- DimPlot(Bleo2_cleaned, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Today.date, "_Bleo2CLEANED_aUMAP_cluster_OGIDsplit.png"), plot = Bleo2cleaned_UMAP_split, width = 45, height = 10, units = "cm")

Bleo2cleaned_lineage_split <- DimPlot(Bleo2_cleaned, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Today.date, "_Bleo2CLEANED_aUMAP_lineage_OGIDsplit.png"), plot = Bleo2cleaned_lineage_split, width = 45, height = 10, units = "cm")

Bleo2cleaned_lineage <- DimPlot(Bleo2_cleaned, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.02) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Today.date, "_Bleo2CLEANED_aUMAP_lineage.png"), plot = Bleo2cleaned_lineage, width = 30, units = "cm")
#-

BDL2cleaned_UMAP <- DimPlot(BDL2_cleaned, reduction = "umap",label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2CLEANED_aUMAP_cluster.png"), plot = BDL2cleaned_UMAP, width = 30, units = "cm")

BDL2cleaned_UMAP_split <- DimPlot(BDL2_cleaned, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2CLEANED_aUMAP_cluster_OGIDsplit.png"), plot = BDL2cleaned_UMAP_split, width = 45, height = 10, units = "cm")

BDL2cleaned_lineage_split <- DimPlot(BDL2_cleaned, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2CLEANED_aUMAP_lineage_OGIDsplit.png"), plot = BDL2cleaned_lineage_split, width = 45, height = 10, units = "cm")

BDL2cleaned_lineage <- DimPlot(BDL2_cleaned, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.02) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Today.date, "_BDL2CLEANED_aUMAP_lineage.png"), plot = BDL2cleaned_lineage, width = 30, units = "cm")

#-

CCl4cleaned_UMAP <- DimPlot(CCl4_cleaned, reduction = "umap",label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Today.date, "_CCl4CLEANED_aUMAP_cluster.png"), plot = CCl4cleaned_UMAP, width = 30, units = "cm")

CCl4cleaned_UMAP_split <- DimPlot(CCl4_cleaned, reduction = "umap", split.by = "Names", label = T, label.size = 2, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Today.date, "_CCl4CLEANED_aUMAP_cluster_OGIDsplit.png"), plot = CCl4cleaned_UMAP_split, width = 45, height = 10, units = "cm")

CCl4cleaned_lineage_split <- DimPlot(CCl4_cleaned, reduction = "umap", group.by = "lineage", split.by = "Names", label = T, label.size = 3, pt.size = 0.01) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Today.date, "_CCl4CLEANED_aUMAP_lineage_OGIDsplit.png"), plot = CCl4cleaned_lineage_split, width = 45, height = 10, units = "cm")

CCl4cleaned_lineage <- DimPlot(CCl4_cleaned, reduction = "umap", group.by = "lineage", label = T, label.size = 3, pt.size = 0.02) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Today.date, "_CCl4CLEANED_aUMAP_lineage.png"), plot = CCl4cleaned_lineage, width = 30, units = "cm")
```