```{r}
# Load required Libraries

library(uwot)
library(Seurat)
library(dplyr)
library(patchwork)
library(ggplot2)
library(RColorBrewer)
library(harmony)
library(cowplot)
library(data.table)

#Set paths

mA5.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Kidney-UUO/"
Bleo2.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Lung-Bleo/"
BDL2.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-BDL/"
CCl4.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-CCl4/"

mA5Output.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Kidney-UUO/Outputs/"
Bleo2Output.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Lung-Bleo/Outputs/"
BDL2Output.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-BDL/Outputs/"
CCl4Output.path  <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Liver-CCl4/Outputs/"

#Set date

Load.date <- "070820"
Save.date <- "160820"
# Set colour palettes

mA5.colpal <- c("#CA9858",	"#FF7F00",	"#C8828D",	"#FFCA62")

Bleo2.colpal <- c("#9683B0",	"#6A3D9A",	"#C8828D",	"#DA98D6")

BDL2.colpal <- c("#8EB26E",	"#88BCB2",	"#33A02C",	"#00CDB3",	"#C8828D",	"#F4A1AF",	"#B2DF8A",	"#AFF1E1")

CCl4.colpal <- c("#74909E",	"#167EDB",	"#C8828D",	"#A6CEE3")

```
```{r}

#Load stuff

mA5 <- readRDS(paste0(mA5.path, Load.date, "_mA5_annotated.RDS"))
Bleo2 <- readRDS(paste0(Bleo2.path, Load.date, "_Bleo2_annotated.RDS"))
BDL2 <- readRDS(paste0(BDL2.path, Load.date, "_BDL2_annotated.RDS"))
CCl4 <- readRDS(paste0(CCl4.path, Load.date, "_CCl4_annotated.RDS"))

mA5_cleaned <- readRDS(paste0(mA5.path, Load.date, "_mA5_CLEANED.RDS"))
Bleo2_cleaned <- readRDS(paste0(Bleo2.path, Load.date, "_Bleo2_CLEANED.RDS"))
BDL2_cleaned <- readRDS(paste0(BDL2Output.path, Load.date, "_BDL2_CLEANED.RDS"))
CCl4_cleaned  <- readRDS(paste0(CCl4.path, Load.date, "_CCl4_CLEANED.RDS"))



```

```{r}

#Find CLEANED markers
mA5CLEANED.markers <- FindAllMarkers(mA5_cleaned, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(mA5CLEANED.markers, file = paste0(mA5Output.path, Save.date, "_mA5CLEANED_ALLmarkers.csv"))

Bleo2CLEANED.markers <- FindAllMarkers(Bleo2_cleaned, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(Bleo2CLEANED.markers, file = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_ALLmarkers.csv"))

BDL2CLEANED.markers <- FindAllMarkers(BDL2_cleaned, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(BDL2CLEANED.markers, file = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_ALLmarkers.csv"))

CCl4CLEANED.markers <- FindAllMarkers(CCl4_cleaned, only.pos = T, min.pct = 0.25, logfc.threshold = 0.25)
write.csv(CCl4CLEANED.markers, file = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_ALLmarkers.csv"))

```

```{R}


# Make Functions

mapCLEANED_Lineage <- function(row){
  cluster <- row[8]
  print(cluster)
  lineage <- annotate$lineage[]
  return(lineage)
}
##!!!!! Can't figure this out !!!!!!##
#Annotate CLEANED marker files
annotate <- read.table(file = paste0(mA5.path,"mA5CLEANED_Annotations",".csv"), header = T, sep = ",", row.names = 1)
mA5CLEANED.markers <- read.csv(paste0(mA5Output.path, Save.date, "_mA5CLEANED_ALLmarkers.csv"))
mA5CLEANED.markers <- data.frame(mA5CLEANED.markers)

mA5CLEANED.markers$lineage <- lapply(mA5CLEANED.markers, function(x) annotate$lineage[match(x, annotate$Cell.type)])

#mA5CLEANED.markers$lineage <- apply(X = mA5CLEANED.markers,1, FUN = mapCLEANED_Lineage)
write.csv(mA5CLEANED.markers, file = paste0(mA5Output.path, Save.date, "_mA5CLEANEDAnno_ALLmarkers.csv"))

annotate <- read.table(file = paste0(Bleo2.path,"Bleo2_Annotations",".csv"), header = T, sep = ",", row.names = 1)
Bleo2CLEANED.markers <- read.csv(paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_ALLmarkers.csv"))
Bleo2CLEANED.markers <- data.frame(Bleo2CLEANED.markers)
Bleo2CLEANED.markers$Cell.type <- apply(X = Bleo2CLEANED.markers,1, FUN = map_Celltype)
Bleo2CLEANED.markers$lineage <- apply(X = Bleo2CLEANED.markers,1, FUN = map_Lineage)
write.csv(Bleo2CLEANED.markers, file = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANEDAnno_ALLmarkers.csv"))

annotate <- read.table(file = paste0(BDL2.path,"BDL2_Annotations",".csv"), header = T, sep = ",", row.names = 1)
BDL2CLEANED.markers <- read.csv(paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_ALLmarkers.csv"))
BDL2CLEANED.markers <- data.frame(BDL2CLEANED.markers)
BDL2CLEANED.markers$Cell.type <- apply(X = BDL2CLEANED.markers,1, FUN = map_Celltype)
BDL2CLEANED.markers$lineage <- apply(X = BDL2CLEANED.markers,1, FUN = map_Lineage)
write.csv(BDL2CLEANED.markers, file = paste0(BDL2Output.path, Save.date, "_BDL2CLEANEDAnno_ALLmarkers.csv"))

annotate <- read.table(file = paste0(CCl4.path,"CCl4_Annotations",".csv"), header = T, sep = ",", row.names = 1)
CCl4CLEANED.markers <- read.csv(paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_ALLmarkers.csv"))
CCl4CLEANED.markers <- data.frame(CCl4CLEANED.markers)
CCl4CLEANED.markers$Cell.type <- apply(X = CCl4CLEANED.markers,1, FUN = map_Celltype)
CCl4CLEANED.markers$lineage <- apply(X = CCl4CLEANED.markers,1, FUN = map_Lineage)
write.csv(CCl4CLEANED.markers, file = paste0(CCl4Output.path, Save.date, "_CCl4CLEANEDAnno_ALLmarkers.csv"))
```

```{r}

#Re_order CLEANED
mA5_cleaned$Cell.type <- factor(mA5$Cell.type, levels = c("Kidney macrophage 1",	"Kidney macrophage 2",	"Kidney macrophage 3",	"Kidney macrophage 4",	"Kidney proliferating macrophage 1",	"Kidney proliferating macrophage 2",	"Kidney IFN-primed macrophage",	"Kidney monocyte",	"Blood Ly6Clo monocyte",	"Healthy blood Ly6Chi monoyte",	"UUO blood Ly6Chi monocyte","Basophil",	"Blood B cell 1",	"Kidney B cell",		"Blood neutrophils",	"Cd4+ T cell 1",	"Cd4+ T cell 2",	"CD8+ T cell 1",	"Cd8+ T cell 2", "NK cell 1",	"NK cell 2",	"ILC2",	"pDC",	"CCR7+ cDC",	"Kidney cDC1",	"Kidney cDC2 1",	"Kidney cDC2 2","Platelet",	"Proliferating", "Kidney endothelial cells"))

Bleo2_cleaned$Cell.type <- factor(Bleo2$Cell.type, levels = c(	"Lung alveolar macrophage 1",	"Lung alveolar macrophage 2",	"Proliferating Lung Alveolar macrophage",	"Lung interstitial macrophage 1",	"Lung interstitial macrophage 2",	"Lung macrophage 3",	"Lung macrophage 4",	"Lung Monocyte","Blood IFN-primed Ly6Chi Monocyte",	"Blood Ly6Chi Monocyte",	"Blood Ly6Clo Monocyte 1",	"Blood Ly6Clo Monocyte 2",	"Lcn2+ Monocyte",	 "Basophil",	"Blood B cell 1",	"Blood B cell 2",	"Lung B Cell 1", "Cd4+ T cell 1", "Blood CD4+ T cell 2",	"Lung CD4+ T cell 2",	 "CD8+ T cell 2",	"Blood CD8+ T cell", "Lung CD8+ T cell",	"Proliferating T cell",	"ILC2",	"NK cell 1",	"CCR7+ cDC",	"cDC1",	"cDC2",	"pDC",	"Proliferating cDC",	"Lung endothelial cells"))

BDL2_cleaned$Cell.type <- factor(BDL2$Cell.type, levels = c("Liver Kupffer Cell 1",	"Liver Kupffer Cell 2",	"Liver macrophage 1",	"Liver macrophage 2",	"Liver macrophage 3",	"Liver macrophage 4",	"Liver macrophage 5",	"Blood IFN-primed Ly6Chi monocyte",	"Blood Ly6Clo monocyte 1",	"Blood Ly6Clo monocyte 2",	"Healthy Blood Ly6Chi monocyte 1",	"Healthy Blood Ly6Chi monocyte 2",	"B cell 1",	"B cell 2",	"B cell 3",	"Basophil",	"Cd4+ T cell 1",	"CD8+ T cell 1",	"T cell 2",	"Neutrophil 1",	"Neutrophil 2",	"NK cell 1",	"NK cell 2",	"pDC",	"cDC1",	"cDC2",	"Proliferating",	"Platelet 1",	"Platelet 2",	"Liver Endothelial Cells"))

CCl4_cleaned$Cell.type <- factor(CCl4$Cell.type, levels = c("Liver Kupffer Cell 1","CCl4 Liver Kupffer Cell 2","Liver macrophage 1","Blood IFN-primed Ly6Chi monocyte","Blood Ly6Clo monocyte","CCl4 Blood Ly6Chi monocyte 1","CCl4 Blood Ly6Chi monocyte 2","CCl4 Blood Ly6Chi monocyte 3","CCl4 Blood Ly6Clo monocyte","Healthy Blood Ly6Chi monocyte","Liver monocyte","B cell 1","B cell 2","B cell 3","Cd4+ T cell 1","CD8+ T cell 1","CD8+ T cell 2","Basophil","Eosinophil","Neutrophil","NK cell 1","NK cell 2","pDC","cDC1","cDC2","Liver CCR7+ cDC","Liver Endothelial Cells",))


# Individual Visualisations GENES -> Heatmap of cluster/marker genes UNCLEANED

mA5CLEANED_top5 <- mA5CLEANED.markers %>% group_by(Cell.type) %>% top_n(n = 5, wt = pct.2)
mA5_cellHM <- DoHeatmap(mA5_cleaned, group.by = "Cell.type", features = mA5CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_celltypeHM.png"), plot = mA5_cellHM, width = 45, units = "cm")

mA5_lineageHM <- DoHeatmap(mA5_cleaned, group.by = "lineage", features = mA5CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_lineage_HM.png"), plot = mA5_lineageHM, width = 45, units = "cm")

#-

Bleo2CLEANED_top5 <- Bleo2CLEANED.markers %>% group_by(Cell.type) %>% top_n(n = 5, wt = pct.2)
Bleo2_cellHM <- DoHeatmap(Bleo2_cleaned, group.by = "Cell.type", features = Bleo2CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_celltypeHM.png"), plot = Bleo2_cellHM, width = 45, units = "cm")

Bleo2_lineageHM <- DoHeatmap(Bleo2_cleaned, group.by = "lineage", features = Bleo2CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_lineage_HM.png"), plot = Bleo2_lineageHM, width = 45, units = "cm")

#-

BDL2CLEANED_top5 <- BDL2CLEANED.markers %>% group_by(Cell.type) %>% top_n(n = 5, wt = pct.2)
BDL2_cellHM <- DoHeatmap(BDL2_cleaned, group.by = "Cell.type", features = BDL2CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_celltypeHM.png"), plot = BDL2_cellHM, width = 45, units = "cm")

BDL2_lineageHM <- DoHeatmap(BDL2_cleaned, group.by = "lineage", features = BDL2CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_lineage_HM.png"), plot = BDL2_lineageHM, width = 45, units = "cm")

#-
CCl4CLEANED_top5 <- CCl4CLEANED.markers %>% group_by(Cell.type) %>% top_n(n = 5, wt = pct.2)
CCl4_cellHM <- DoHeatmap(CCl4_cleaned, group.by = "Cell.type", features = CCl4CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_celltypeHM.png"), plot = CCl4_cellHM, width = 45, units = "cm")

CCl4_lineageHM <- DoHeatmap(CCl4_cleaned, group.by = "lineage", features = CCl4CLEANED_top5$gene) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_lineage_HM.png"), plot = CCl4_lineageHM, width = 45, units = "cm")

```

```{r}
#Uncleaned
# Make Functions
map_Celltype <- function(row){
  cluster <- row[7]
  cluster <- as.numeric(cluster) + 1
  print(cluster)
  Cell.type <- annotate$Cell.type[cluster]
  return(Cell.type)
}

map_Lineage <- function(row){
  cluster <- row[7]
  cluster <- as.numeric(cluster) + 1
  lineage <- annotate$lineage[cluster]
  return(lineage)
}

#Annotate marker files
annotate <- read.table(file = paste0(mA5.path,"mA5_Annotations",".csv"), header = T, sep = ",", row.names = 1)
mA5.markers <- read.csv(paste0(mA5Output.path, Load.date, "_mA5_ALLmarkers.csv"))
mA5.markers <- data.frame(mA5CLEANED.markers)
mA5.markers$Cell.type <- apply(X = mA5.markers,1, FUN = map_Celltype)
mA5.markers$lineage <- apply(X = mA5.markers,1, FUN = map_Lineage)
write.csv(mA5.markers, file = paste0(mA5Output.path, Save.date, "_mA5Anno_ALLmarkers.csv"))

annotate <- read.table(file = paste0(Bleo2.path,"Bleo2_Annotations",".csv"), header = T, sep = ",", row.names = 1)
Bleo2.markers <- read.csv(paste0(Bleo2Output.path, Load.date, "_Bleo2_ALLmarkers.csv"))
Bleo2.markers <- data.frame(Bleo2.markers)
Bleo2.markers$Cell.type <- apply(X = Bleo2.markers,1, FUN = map_Celltype)
Bleo2.markers$lineage <- apply(X = Bleo2.markers,1, FUN = map_Lineage)
write.csv(Bleo2.markers, file = paste0(Bleo2Output.path, Save.date, "_Bleo2Anno_ALLmarkers.csv"))

annotate <- read.table(file = paste0(BDL2.path,"BDL2_Annotations",".csv"), header = T, sep = ",", row.names = 1)
BDL2.markers <- read.csv(paste0(BDL2Output.path, Load.date, "_BDL2_ALLmarkers.csv"))
BDL2.markers <- data.frame(BDL2.markers)
BDL2.markers$Cell.type <- apply(X = BDL2.markers,1, FUN = map_Celltype)
BDL2.markers$lineage <- apply(X = BDL2.markers,1, FUN = map_Lineage)
write.csv(BDL2.markers, file = paste0(BDL2Output.path, Save.date, "_BDL2Anno_ALLmarkers.csv"))

annotate <- read.table(file = paste0(CCl4.path,"CCl4_Annotations",".csv"), header = T, sep = ",", row.names = 1)
CCl4.markers <- read.csv(paste0(CCl4Output.path, Load.date, "_CCl4_ALLmarkers.csv"))
CCl4.markers <- data.frame(CCl4.markers)
CCl4.markers$Cell.type <- apply(X = CCl4.markers,1, FUN = map_Celltype)
CCl4.markers$lineage <- apply(X = CCl4.markers,1, FUN = map_Lineage)
write.csv(CCl4.markers, file = paste0(CCl4Output.path, Save.date, "_CCl4Anno_ALLmarkers.csv"))

```

```{r}
# Individual Visualisations GENES -> Heatmap of cluster/marker genes UNCLEANED
mA5_top5 <- mA5.markers %>% group_by(cluster) %>% top_n(n = 5, wt = avg_logFC)
mA5_clusterHM <- DoHeatmap(mA5, group.by = "seurat_clusters", features = mA5_top5$gene, label = T, slot = "data") + NoLegend()
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5_clusterHM.png"), plot = mA5_clusterHM, height = 45, units = "cm")

#-
Bleo2_top5 <- Bleo2.markers %>% group_by(cluster) %>% top_n(n = 5, wt = pct.2)
Bleo2_clusterHM <- DoHeatmap(Bleo2, features = Bleo2_top5$gene) + NoLegend()
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2_clusterHM.png"), plot = Bleo2_clusterHM, width = 45, units = "cm")

#-

BDL2_top5 <- BDL2.markers %>% group_by(cluster) %>% top_n(n = 5, wt = pct.2)
BDL2_clusterHM <- DoHeatmap(BDL2, features = BDL2_top5$gene) + NoLegend()
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2_clusterHM.png"), plot = BDL2_clusterHM, width = 45, units = "cm")

#-

CCl4_top5 <- CCl4.markers %>% group_by(cluster) %>% top_n(n = 5, wt = pct.2)
CCl4_clusterHM <- DoHeatmap(CCl4, features = CCl4_top5$gene) + NoLegend()
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4_clusterHM.png"), plot = CCl4_clusterHM, width = 45, units = "cm")

```

# Proportion Vis - Cell
```{r}

# Individual Visualisations CELL -> Proportion
### Dataset membership vary by cell type ###
mA5 <- mA5_cleaned
Bleo2 <- Bleo2_cleaned
BDL2 <- BDL2_cleaned
CCl4 <- CCl4_cleaned


Idents(mA5) <- "Names"
mA5$Names <- factor(mA5$Names, levels = c("UUO-Kidney", "H-Kidney", "UUO-Blood", "H-Blood"))
table(Idents(mA5))
mA5_NameCellProp <- prop.table(table(Idents(mA5), mA5$Cell.type))
mA5_NameCellProp
mA5_CellProp <- as.data.frame(mA5_NameCellProp)

names(mA5_CellProp)[names(mA5_CellProp) == "Var1"] <- "Dataset"
names(mA5_CellProp)[names(mA5_CellProp) == "Var2"] <- "Cell_type"
names(mA5_CellProp)[names(mA5_CellProp) == "Freq"] <- "Proportion"

plot_mA5_CellPropBAR <- ggplot(mA5_CellProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = mA5.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_CellPropBAR_Celltype.png"), plot = plot_mA5_CellPropBAR, width = 30, units = "cm")

plot_mA5_CellPropBAR_Dataset <- ggplot(mA5_CellProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_CellPropBAR_Dataset.png"), plot = plot_mA5_CellPropBAR_Dataset, width = 30, units = "cm")

#-
Bleo2$Names <- factor(Bleo2$Names, levels = c("Bleo-Lung", "H-Lung", "Bleo-Blood", "H-Blood"))

Idents(Bleo2) <- "Names"
table(Idents(Bleo2))
Bleo2_NameCellProp <- prop.table(table(Idents(Bleo2), Bleo2$Cell.type))
Bleo2_NameCellProp
Bleo2_CellProp <- as.data.frame(Bleo2_NameCellProp)

names(Bleo2_CellProp)[names(Bleo2_CellProp) == "Var1"] <- "Dataset"
names(Bleo2_CellProp)[names(Bleo2_CellProp) == "Var2"] <- "Cell_type"
names(Bleo2_CellProp)[names(Bleo2_CellProp) == "Freq"] <- "Proportion"

plot_Bleo2_CellPropBAR <- ggplot(Bleo2_CellProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = Bleo2.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_CellPropBAR_Celltype.png"), plot = plot_Bleo2_CellPropBAR, width = 30, units = "cm")

plot_Bleo2_CellPropBAR_Dataset <- ggplot(Bleo2_CellProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_CellPropBAR_Dataset.png"), plot = plot_Bleo2_CellPropBAR_Dataset, width = 30, units = "cm")

#-
BDL2$Names <- factor(BDL2$Names, levels = c("BDL-Liver-A", "BDL-Liver-B", "H-Liver-A", "H-Liver-B", "BDL-Blood-A", "BDL-Blood-B", "H-Blood-A", "H-Blood-B"))

Idents(BDL2) <- "Names"
table(Idents(BDL2))
BDL2_NameCellProp <- prop.table(table(Idents(BDL2), BDL2$Cell.type))
BDL2_NameCellProp
BDL2_CellProp <- as.data.frame(BDL2_NameCellProp)

names(BDL2_CellProp)[names(BDL2_CellProp) == "Var1"] <- "Dataset"
names(BDL2_CellProp)[names(BDL2_CellProp) == "Var2"] <- "Cell_type"
names(BDL2_CellProp)[names(BDL2_CellProp) == "Freq"] <- "Proportion"

plot_BDL2_CellPropBAR <- ggplot(BDL2_CellProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = BDL2.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_CellPropBAR_Celltype.png"), plot = plot_BDL2_CellPropBAR, width = 30, units = "cm")

plot_BDL2_CellPropBAR_Dataset <- ggplot(BDL2_CellProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_CellPropBAR_Dataset.png"), plot = plot_BDL2_CellPropBAR_Dataset, width = 30, units = "cm")

#-

CCl4$Names <- factor(CCl4$Names, levels = c("CCl4-Liver", "H-Liver", "CCl4-Blood", "H-Blood"))

Idents(CCl4) <- "Names"
table(Idents(CCl4))
CCl4_NameCellProp <- prop.table(table(Idents(CCl4), CCl4$Cell.type))
CCl4_NameCellProp
CCl4_CellProp <- as.data.frame(CCl4_NameCellProp)

names(CCl4_CellProp)[names(CCl4_CellProp) == "Var1"] <- "Dataset"
names(CCl4_CellProp)[names(CCl4_CellProp) == "Var2"] <- "Cell_type"
names(CCl4_CellProp)[names(CCl4_CellProp) == "Freq"] <- "Proportion"

plot_CCl4_CellPropBAR <- ggplot(CCl4_CellProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = CCl4.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_CellPropBAR_Celltype.png"), plot = plot_CCl4_CellPropBAR, width = 30, units = "cm")

plot_CCl4_CellPropBAR_Dataset <- ggplot(CCl4_CellProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_CellPropBAR_Dataset.png"), plot = plot_CCl4_CellPropBAR_Dataset, width = 30, units = "cm")


### Cell type membership vary by dataset ###

Idents(mA5) <- "Cell.type"
table(Idents(mA5))
mA5_CellNameProp <- prop.table(table(Idents(mA5), mA5$Names))
mA5_CellNameProp
mA5_DataProp <- as.data.frame(mA5_CellNameProp)

names(mA5_DataProp)[names(mA5_DataProp) == "Var1"] <- "Cell_type"
names(mA5_DataProp)[names(mA5_DataProp) == "Var2"] <- "Dataset"
names(mA5_DataProp)[names(mA5_DataProp) == "Freq"] <- "Proportion"

plot_mA5_DataPropBAR <- ggplot(mA5_DataProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = mA5.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_DataPropBAR_Celltype.png"), plot = plot_mA5_DataPropBAR, width = 30, units = "cm")

plot_mA5_DataPropBAR_Dataset <- ggplot(mA5_DataProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_DataPropBAR_Dataset.png"), plot = plot_mA5_DataPropBAR_Dataset, width = 30, units = "cm")

#-

Idents(Bleo2) <- "Cell.type"
table(Idents(Bleo2))
Bleo2_CellNameProp <- prop.table(table(Idents(Bleo2), Bleo2$Names))
Bleo2_CellNameProp
Bleo2_DataProp <- as.data.frame(Bleo2_CellNameProp)

names(Bleo2_DataProp)[names(Bleo2_DataProp) == "Var1"] <- "Cell_type"
names(Bleo2_DataProp)[names(Bleo2_DataProp) == "Var2"] <- "Dataset"
names(Bleo2_DataProp)[names(Bleo2_DataProp) == "Freq"] <- "Proportion"


plot_Bleo2_DataPropBAR <- ggplot(Bleo2_DataProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = Bleo2.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_DataPropBAR_Celltype.png"), plot = plot_Bleo2_DataPropBAR, width = 30, units = "cm")

plot_Bleo2_DataPropBAR_Dataset <- ggplot(Bleo2_DataProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_DataPropBAR_Dataset.png"), plot = plot_Bleo2_DataPropBAR_Dataset, width = 30, units = "cm")

#-

Idents(BDL2) <- "Cell.type"
table(Idents(BDL2))
BDL2_CellNameProp <- prop.table(table(Idents(BDL2), BDL2$Names))
BDL2_CellNameProp
BDL2_DataProp <- as.data.frame(BDL2_CellNameProp)

names(BDL2_DataProp)[names(BDL2_DataProp) == "Var1"] <- "Cell_type"
names(BDL2_DataProp)[names(BDL2_DataProp) == "Var2"] <- "Dataset"
names(BDL2_DataProp)[names(BDL2_DataProp) == "Freq"] <- "Proportion"

plot_BDL2_DataPropBAR <- ggplot(BDL2_DataProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = BDL2.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_DataPropBAR_Celltype.png"), plot = plot_BDL2_DataPropBAR, width = 30, units = "cm")

plot_BDL2_DataPropBAR_Dataset <- ggplot(BDL2_DataProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_DataPropBAR_Dataset.png"), plot = plot_BDL2_DataPropBAR_Dataset, width = 30, units = "cm")


#-

Idents(CCl4) <- "Cell.type"
table(Idents(CCl4))
CCl4_CellNameProp <- prop.table(table(Idents(CCl4), CCl4$Names))
CCl4_CellNameProp
CCl4_DataProp <- as.data.frame(CCl4_CellNameProp)

names(CCl4_DataProp)[names(CCl4_DataProp) == "Var1"] <- "Cell_type"
names(CCl4_DataProp)[names(CCl4_DataProp) == "Var2"] <- "Dataset"
names(CCl4_DataProp)[names(CCl4_DataProp) == "Freq"] <- "Proportion"

plot_CCl4_DataPropBAR <- ggplot(CCl4_DataProp, aes(fill=Dataset, y=Proportion, x=Cell_type)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = CCl4.colpal) + theme(axis.text.x.bottom = element_text(angle = 45, hjust = 1))
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_DataPropBAR_Celltype.png"), plot = plot_CCl4_DataPropBAR, width = 30, units = "cm")

plot_CCl4_DataPropBAR_Dataset <- ggplot(CCl4_DataProp, aes(fill=Cell_type, y=Proportion, x=Dataset)) + geom_bar(position="fill", stat="identity")
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_DataPropBAR_Dataset.png"), plot = plot_CCl4_DataPropBAR_Dataset, width = 30, units = "cm")

```
# Proportion Vis - Lineage
```{r}
# Individual Visualisations LINEAGE -> Proportion

### Dataset membership vary by lineage ###
Idents(mA5) <- "Names"
table(Idents(mA5))
mA5_NameLinProp <- prop.table(table(Idents(mA5), mA5$lineage))
mA5_LinProp <- as.data.frame(mA5_NameLinProp)

names(mA5_LinProp)[names(mA5_LinProp) == "Var1"] <- "Dataset"
names(mA5_LinProp)[names(mA5_LinProp) == "Var2"] <- "Lineage"
names(mA5_LinProp)[names(mA5_LinProp) == "Freq"] <- "Proportion"

mA5_plot1 <- ggplot(mA5_LinProp, aes(fill=Dataset, y=Proportion, x=Lineage)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = mA5.colpal)

ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_DataLinPropBAR.png"), plot = mA5_plot1, width = 30, units = "cm")

mA5_plot2 <- mA5_plot1 + coord_polar(theta = "x")
mA5_plot3 <- mA5_plot1 + coord_polar(theta = "y")
mA5_plot1_pie <- mA5_plot2 + mA5_plot3
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_DataLinPropPIE.png"), plot = mA5_plot1_pie, width = 40, units = "cm")

#-
Idents(Bleo2) <- "Names"
table(Idents(Bleo2))
Bleo2_NameLinProp <- prop.table(table(Idents(Bleo2), Bleo2$lineage))
Bleo2_LinProp <- as.data.frame(Bleo2_NameLinProp)

names(Bleo2_LinProp)[names(Bleo2_LinProp) == "Var1"] <- "Dataset"
names(Bleo2_LinProp)[names(Bleo2_LinProp) == "Var2"] <- "Lineage"
names(Bleo2_LinProp)[names(Bleo2_LinProp) == "Freq"] <- "Proportion"

Bleo2_plot1 <- ggplot(Bleo2_LinProp, aes(fill=Dataset, y=Proportion, x=Lineage)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = Bleo2.colpal)

ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_DataLinPropBAR.png"), plot = Bleo2_plot1, width = 30, units = "cm")

Bleo2_plot2 <- Bleo2_plot1 + coord_polar(theta = "x")
Bleo2_plot3 <- Bleo2_plot1 + coord_polar(theta = "y")
Bleo2_plot1_pie <- Bleo2_plot2 + Bleo2_plot3
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_DataLinPropPIE.png"), plot = Bleo2_plot1_pie, width = 40, units = "cm")

#-
Idents(BDL2) <- "Names"
table(Idents(BDL2))
BDL2_NameLinProp <- prop.table(table(Idents(BDL2), BDL2$lineage))
BDL2_LinProp <- as.data.frame(BDL2_NameLinProp)

names(BDL2_LinProp)[names(BDL2_LinProp) == "Var1"] <- "Dataset"
names(BDL2_LinProp)[names(BDL2_LinProp) == "Var2"] <- "Lineage"
names(BDL2_LinProp)[names(BDL2_LinProp) == "Freq"] <- "Proportion"


BDL2_plot1 <- ggplot(BDL2_LinProp, aes(fill=Dataset, y=Proportion, x=Lineage)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = BDL2.colpal)

ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_DataLinPropBAR.png"), plot = BDL2_plot1, width = 30, units = "cm")

BDL2_plot2 <- BDL2_plot1 + coord_polar(theta = "x")
BDL2_plot3 <- BDL2_plot1 + coord_polar(theta = "y")
BDL2_plot1_pie <- BDL2_plot2 + BDL2_plot3
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_DataLinPropPIE.png"), plot = BDL2_plot1_pie, width = 40, units = "cm")

#-

Idents(CCl4) <- "Names"
table(Idents(CCl4))
CCl4_NameLinProp <- prop.table(table(Idents(CCl4), CCl4$lineage))
CCl4_LinProp <- as.data.frame(CCl4_NameLinProp)

names(CCl4_LinProp)[names(CCl4_LinProp) == "Var1"] <- "Dataset"
names(CCl4_LinProp)[names(CCl4_LinProp) == "Var2"] <- "Lineage"
names(CCl4_LinProp)[names(CCl4_LinProp) == "Freq"] <- "Proportion"

CCl4_plot1 <- ggplot(CCl4_LinProp, aes(fill=Dataset, y=Proportion, x=Lineage)) + geom_bar(position="fill", stat="identity") + scale_fill_manual(values = CCl4.colpal)

ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_DataLinPropBAR.png"), plot = CCl4_plot1, width = 30, units = "cm")

CCl4_plot2 <- CCl4_plot1 + coord_polar(theta = "x")
CCl4_plot3 <- CCl4_plot1 + coord_polar(theta = "y")
CCl4_plot1_pie <- CCl4_plot2 + CCl4_plot3
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_DataLinPropPIE.png"), plot = CCl4_plot1_pie, width = 40, units = "cm")
### Lineage membership vary by dataset ###

Idents(mA5) <- "lineage"
table(Idents(mA5))
mA5_LinNameProp <- prop.table(table(Idents(mA5), mA5$Names))
mA5_LinNameProp <- as.data.frame(mA5_LinNameProp)

names(mA5_LinNameProp)[names(mA5_LinNameProp) == "Var1"] <- "Lineage"
names(mA5_LinNameProp)[names(mA5_LinNameProp) == "Var2"] <- "Dataset"
names(mA5_LinNameProp)[names(mA5_LinNameProp) == "Freq"] <- "Proportion"

plot_LinNameBAR <- ggplot(mA5_LinNameProp, aes(fill=Lineage, y=Proportion, x=Dataset)) + geom_bar(position ="fill", stat="identity")
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_LinDataPropBAR.png"), plot = plot_LinNameBAR, width = 30, units = "cm")

plotLinNamePIE1 <- plot_LinNameBAR + coord_polar(theta = "x")
plotLinNamePIE2 <- plot_LinNameBAR + coord_polar(theta = "y")
plot_LinNamePIE <- plotLinNamePIE1 + plotLinNamePIE2
ggsave(filename = paste0(mA5Output.path, Save.date, "_mA5CLEANED_LinDataPropPIE.png"), plot = plot_LinNamePIE, width = 45, units = "cm")

#-
Idents(Bleo2) <- "lineage"
table(Idents(Bleo2))
Bleo2_LinNameProp <- prop.table(table(Idents(Bleo2), Bleo2$Names))
Bleo2_LinNameProp <- as.data.frame(Bleo2_LinNameProp)

names(Bleo2_LinNameProp)[names(Bleo2_LinNameProp) == "Var1"] <- "Lineage"
names(Bleo2_LinNameProp)[names(Bleo2_LinNameProp) == "Var2"] <- "Dataset"
names(Bleo2_LinNameProp)[names(Bleo2_LinNameProp) == "Freq"] <- "Proportion"

plot_LinNameBAR <- ggplot(Bleo2_LinNameProp, aes(fill=Lineage, y=Proportion, x=Dataset)) + geom_bar(position ="fill", stat="identity")
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_LinDataPropBAR.png"), plot = plot_LinNameBAR, width = 30, units = "cm")

plotLinNamePIE1 <- plot_LinNameBAR + coord_polar(theta = "x")
plotLinNamePIE2 <- plot_LinNameBAR + coord_polar(theta = "y")
plot_LinNamePIE <- plotLinNamePIE1 + plotLinNamePIE2
ggsave(filename = paste0(Bleo2Output.path, Save.date, "_Bleo2CLEANED_LinDataPropPIE.png"), plot = plot_LinNamePIE, width = 45, units = "cm")

#-
Idents(BDL2) <- "lineage"
table(Idents(BDL2))
BDL2_LinNameProp <- prop.table(table(Idents(BDL2), BDL2$Names))
BDL2_LinNameProp <- as.data.frame(BDL2_LinNameProp)

names(BDL2_LinNameProp)[names(BDL2_LinNameProp) == "Var1"] <- "Lineage"
names(BDL2_LinNameProp)[names(BDL2_LinNameProp) == "Var2"] <- "Dataset"
names(BDL2_LinNameProp)[names(BDL2_LinNameProp) == "Freq"] <- "Proportion"

plot_LinNameBAR <- ggplot(BDL2_LinNameProp, aes(fill=Lineage, y=Proportion, x=Dataset)) + geom_bar(position ="fill", stat="identity")
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_LinDataPropBAR.png"), plot = plot_LinNameBAR, width = 30, units = "cm")

plotLinNamePIE1 <- plot_LinNameBAR + coord_polar(theta = "x")
plotLinNamePIE2 <- plot_LinNameBAR + coord_polar(theta = "y")
plot_LinNamePIE <- plotLinNamePIE1 + plotLinNamePIE2
ggsave(filename = paste0(BDL2Output.path, Save.date, "_BDL2CLEANED_LinDataPropPIE.png"), plot = plot_LinNamePIE, width = 45, units = "cm")

#-
Idents(CCl4) <- "lineage"
table(Idents(CCl4))
CCl4_LinNameProp <- prop.table(table(Idents(CCl4), CCl4$Names))
CCl4_LinNameProp <- as.data.frame(CCl4_LinNameProp)

names(CCl4_LinNameProp)[names(CCl4_LinNameProp) == "Var1"] <- "Lineage"
names(CCl4_LinNameProp)[names(CCl4_LinNameProp) == "Var2"] <- "Dataset"
names(CCl4_LinNameProp)[names(CCl4_LinNameProp) == "Freq"] <- "Proportion"

plot_LinNameBAR <- ggplot(CCl4_LinNameProp, aes(fill=Lineage, y=Proportion, x=Dataset)) + geom_bar(position ="fill", stat="identity")
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_LinDataPropBAR.png"), plot = plot_LinNameBAR, width = 30, units = "cm")

plotLinNamePIE1 <- plot_LinNameBAR + coord_polar(theta = "x")
plotLinNamePIE2 <- plot_LinNameBAR + coord_polar(theta = "y")
plot_LinNamePIE <- plotLinNamePIE1 + plotLinNamePIE2
ggsave(filename = paste0(CCl4Output.path, Save.date, "_CCl4CLEANED_LinDataPropPIE.png"), plot = plot_LinNamePIE, width = 45, units = "cm")


```


