---
title: "R Notebook"
author: mjdioli
date: 17/08/2020
output: html_notebook
---
```{r}
# rerun IndieAnnotate
#Rerun HM -> Doesn't seem to work, move on since it's just graphs and we can revisit this later.
# Re-run Harmony based on Prakash's stuff
library(uwot)
library(Seurat)
library(dplyr)
library(patchwork)
library(ggplot2)
library(RColorBrewer)
library(harmony)
library(cowplot)
library(data.table)

harmony.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Merge/"
harmonyOutput.path <- "/home/mjdioli/Documents/Ingrid/Harmony_Test2_SSH/Merge/Outputs/"

# Load data
harTest2 <- readRDS(paste0(harmony.path, "120820_HarmonyTest2_UMAP.RDS"))

```

```{R}

#Annotate HarTest2 cluster
harTest2_cluster.annotation <- c("Ly6C hi monocyte 1",	"Tissue resident macrophage 1",	"Ly6C lo monocyte 1",	"B cell 1",	"Macrophage 2",	"NK cell 1",	"CD8+ T cell 1",	"Cd4+ T cell 1",	"Macrophage 1",	"Neutrophil",	"cDC2",	"NKT cell",	"Tissue resident macrophage 2",	"pDC",	"cDC1",	"B cell 2",	"IFN-primed macrophage",	"Proliferating 1",	"Proliferating 2",	"Ly6C hi monocyte 2",	"Macrophage 3",	"B cell/monoycte doublet",	"Ctla4+ T cell",	"Tissue resident macrophage 3",	"Endothelial cells ",	"Tissue resident macrophage 4",	"Basophi",	"B cell/monocytedoublet",	"B cell/T cell doublet",	"CCR7+ cDC",	"Platelet/monocyte doublet",	"IFN-primed T cell",	"T cell/monocyte doublet",	"B cell 3",	"Platelet",	"NK cell/monocyte doublet")

names(harTest2_cluster.annotation) <- levels(harTest2)
harTest2 <- RenameIdents(harTest2, harTest2_cluster.annotation)

harTest2_cell.data <- data.table(barcode = colnames(harTest2),
                             Cell.type = Idents(harTest2))

harTest2_cell.data <- data.frame(harTest2_cell.data, row.names = harTest2_cell.data$barcode)
harTest2_cell.data$barcode <- NULL
harTest2 <- AddMetaData(harTest2, harTest2_cell.data, col.name = "Cell.type")

#Annotate lineage

harTest2_lineage.annotation <- c("MP",	"MP",	"MP",	"B cell",	"MP",	"T cell/ILC",	"T cell/ILC",	"T cell/ILC",	"MP",	"Neutrophil",	"MP",	"T cell/ILC",	"MP",	"MP",	"MP",	"B cell",	"MP",	"Proliferating",	"Proliferating",	"MP",	"MP",	"Doublet",	"T cell/ILC",	"MP",	"Enodthelia",	"MP",	"Basophil",	"Doublet",	"Doublet",	"MP",	"Doublet",	"T cell/ILC",	"Doublet",	"B cell",	"Platelet",	"Doublet")

names(harTest2_lineage.annotation) <- levels(harTest2)
harTest2 <- RenameIdents(harTest2, harTest2_lineage.annotation)

harTest2_lin.data <- data.table(barcode = colnames(harTest2),
                             lineage = Idents(harTest2))

harTest2_lin.data <- data.frame(harTest2_lin.data, row.names = harTest2_lin.data$barcode)
harTest2_lin.data$barcode <- NULL
harTest2 <- AddMetaData(harTest2, harTest2_lin.data, col.name = "lineage")

```

```{r}
#Clean out doublets

harTest2_cleaned <- subset(harTest2, subset = lineage != "Doublet")

harTest2_cleaned$Condition <- factor(harTest2_cleaned$Condition, levels = c("Healthy", "Fibrotic"))
```

```{r}
# Visualisations
plot_harCluster <- DimPlot(harTest2, reduction = "umap", label = TRUE) + NoLegend()
ggsave(filename = paste0(harmonyOutput.path, "180820_Test2_UMAPcl.png"), width = 30, units = "cm")


plot_harCluster <- DimPlot(harTest2_cleaned, group.by = "Cell.type", reduction = "umap", label = TRUE, label.size = 3) + NoLegend()
ggsave(filename = paste0(harmonyOutput.path, "170820_Test2CLEANED_UMAPcl.png"), width = 30, units = "cm")

plot_harCluster <- DimPlot(harTest2_cleaned, group.by = "Cell.type", split.by = "Condition" ,reduction = "umap", label = TRUE, label.size = 3) + NoLegend()
ggsave(filename = paste0(harmonyOutput.path, "170820_Test2CLEANED_UMAPcl_Cond.png"), width = 45, units = "cm")

```
